#ifndef CONTROLLER_H
#define CONTROLLER_H

#include <Eigen/Dense>
#include <string>

/**
 * @class Controller
 * @brief Full-state feedback LQR controller for 2D rocket
 * 
 * Control law: u = -K * (x - x_ref)
 * Where:
 *   u = [T, alpha] (thrust and gimbal angle)
 *   x = [x, xdot, y, ydot, theta, thetadot]
 *   K = 2x6 LQR gain matrix
 */
class Controller {
private:
    // LQR gain matrix (2x6): row 0 = thrust, row 1 = gimbal angle
    Eigen::Matrix<double, 2, 6> K;
    
    // Control saturation limits
    double max_thrust;
    double max_gimbal;
    
public:
    /**
     * @brief Constructor with default saturation limits
     * @param max_thrust Maximum thrust command (N), default 10.0
     * @param max_gimbal Maximum gimbal angle (rad), default 0.785 (~45 degrees)
     */
    Controller(double max_thrust = 10.0, double max_gimbal = 0.785);
    
    /**
     * @brief Load LQR gains from JSON file
     * @param filename Path to lqr_gains.json generated by Python script
     * @return true if loaded successfully
     */
    bool load_gains_from_json(const std::string& filename);
    
    /**
     * @brief Compute control outputs using LQR law
     * @param state Current rocket state [x, xdot, y, ydot, theta, thetadot]
     * @param state_ref Reference state (setpoint)
     * @return [T, alpha] control commands (saturated)
     */
    Eigen::Vector2d compute_control(const Eigen::VectorXd& state,
                                    const Eigen::VectorXd& state_ref);
    
    /**
     * @brief Get current K matrix
     * @return Reference to K matrix
     */
    const Eigen::Matrix<double, 2, 6>& get_gains() const { return K; }
    
    /**
     * @brief Set K matrix directly
     * @param new_K 2x6 gain matrix
     */
    void set_gains(const Eigen::Matrix<double, 2, 6>& new_K);
};

#endif // CONTROLLER_H
